=== adam-coster/adam-coster/projects/site/src/routes/blog/post.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"title": "Blog Post",
	"type": "object",
	"required": ["slug", "title", "description", "tags", "publishedAt"],
	"properties": {
		"slug": {
			"type": "string",
			"description": "The unique identifier for the blog post"
		},
		"title": {
			"type": "string",
			"maxLength": 75
		},
		"description": {
			"type": "string",
			"maxLength": 175
		},
		"canonical": {
			"type": "string",
			"format": "uri"
		},
		"tags": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/tag"
			}
		},
		"legacySlug": { "type": "string" },
		"editedAt": {
			"type": "string",
			"format": "date-time"
		},
		"publishedAt": {
			"type": "string",
			"format": "date-time"
		}
	},
	"definitions": {
		"tag": {
			"enum": [
				"math",
				"learn",
				"statistics",
				"simulation",
				"programming",
				"python",
				"science",
				"biology",
				"experiments",
				"tools",
				"productivity",
				"node",
				"webdev",
				"javascript",
				"documentation",
				"writing",
				"devops",
				"discuss",
				"computer-science",
				"encoding",
				"serialization",
				"communication",
				"binary",
				"beginners",
				"data",
				"linux",
				"windows",
				"docker",
				"html",
				"css",
				"email",
				"marketing",
				"typescript",
				"tutorial",
				"video",
				"expressjs",
				"json",
				"phd",
				"vscode",
				"motivation",
				"mental-health",
				"adhd",
				"life",
				"philosophy",
				"privilege",
				"definition",
				"evolution",
				"media",
				"critique",
				"notion",
				"ergonomics",
				"health",
				"permissions",
				"security",
				"authentication",
				"npm",
				"testing",
				"tdd",
				"mochajs",
				"gamedev",
				"google",
				"business",
				"apple",
				"cors",
				"cookies",
				"http",
				"jsdoc"
			]
		}
	}
}

=== adam-coster/adam-coster/projects/site/src/routes/blog/(posts)/looper-allele-frequency-problem/meta.json
{
	"$schema": "../../post.schema.json",
	"slug": "looper-allele-frequency-problem",
	"title": "Allele frequency problem in \"Looper\"",
	"description": "Time travel is always a nonsense generator, but \"Looper\" kicks it up a notch with impossibly rapid evolution.\n",
	"publishedAt": "2013-01-12T07:55:00.402Z",
	"legacySlug": "allele-frequency-problem-in-looper",
	"tags": ["science", "biology", "evolution", "media", "critique"]
}

=== adam-coster/adam-coster/projects/site/src/routes/blog/(posts)/image-correction-microscopy/meta.json
{
	"$schema": "../../post.schema.json",
	"slug": "image-correction-microscopy",
	"title": "Image Correction Microscopy",
	"description": "Fluorescence microscopy images are plagued with background noise. The standard approach to correcting for this is insufficient.\n",
	"editedAt": "2021-11-28T00:00:00.000Z",
	"publishedAt": "2014-05-31T00:00:00.000Z",
	"legacySlug": "image-correction-in-fluorescence-microscopy",
	"tags": ["science", "biology", "phd"]
}

=== adam-coster/adam-coster/projects/site/src/routes/blog/(posts)/cloning-ligation-multiple-inserts/meta.json
{
	"$schema": "../post.schema.json",
	"slug": "cloning-ligation-multiple-inserts",
	"title": "Cloning trick: ligation of multiple inserts",
	"description": "Stitching multiple DNA inserts together through standard cloning yields terrible results. But you can amplify the rare successes!\n",
	"editedAt": "2013-02-26T00:00:00.000Z",
	"publishedAt": "2011-07-11T00:00:00.000Z",
	"legacySlug": "cloning-trick-ligation-of-multiple-inserts",
	"tags": [
		"science",
		"biology",
		"experiments",
		"tools",
		"productivity",
		"learn"
	]
}

=== adam-coster/adam-coster/projects/site/src/routes/blog/birthday-problem-python/meta.json
{
	"$schema": "../post.schema.json",
	"slug": "birthday-problem-python",
	"title": "The \"Birthday Problem\" simulated with Python",
	"description": "There's better than a 50% chance that 2 of any 25 random people will share the same birthday. That's hard to believe. Let's simulate it!\n",
	"publishedAt": "2011-07-13T00:00:00.000Z",
	"legacySlug": "python-shared-birthdays",
	"tags": ["math", "learn", "statistics", "simulation", "programming", "python"]
}

=== adam-coster/adam-coster/projects/site/src/routes/blog/(posts)/monty-hall-python/meta.json
{
	"$schema": "../../post.schema.json",
	"slug": "monty-hall-python",
	"title": "The Monty Hall problem modeled in Python",
	"description": "The Monty Hall problem is a classic example of how difficult statistical reasoning can be. Let's simulate it in Python.\n",
	"publishedAt": "2011-02-20T00:00:00.000Z",
	"legacySlug": "python-monty-hall-modeling",
	"tags": ["math", "learn", "statistics", "simulation", "programming", "python"]
}

=== adam-coster/adam-coster/projects/site/src/routes/blog/(posts)/geb-wondrousness-python/meta.json
{
	"$schema": "../../post.schema.json",
	"slug": "geb-wondrousness-python",
	"title": "\"GÃ¶del, Escher, Bach\": Wondrousness in Python",
	"description": "In GEB the Tortoise and Achilles describe a number property they call \"Wondrousness\". It creates a fascinating graph.\n",
	"publishedAt": "2011-01-15T00:00:00.000Z",
	"legacySlug": "python-geb-and-wondrousness",
	"tags": ["math", "learn", "simulation", "programming", "python"]
}
